import math
from geometry import box, ellipsoid, group, loft, rod


def build_vehicle(spec, palette, cockpit_width):
    p = palette
    car = group("DINORACE_CAR")
    wb, tw = spec["wheelbase"], spec["trackWidth"]
    box("DINORACE_FLOOR",(0,0.28,0),(3.2,0.12,6.8),p["carbon"],car)
    loft("DINORACE_MONOCOQUE",[(-2.8,.7,.42,.4),(-1.8,.85,.65,.55),(-.5,.7,.72,.42),(.7,.72,.65,.42),(1.5,.72,.48,.28),(3.4,.51,.22,.14)],p["paint"],car)
    box("DINORACE_COCKPIT_RECESS",(0,1.02,-.05),(cockpit_width,0.1,1.8),p["black"],car)
    for side in [-1,1]:
        for z in [-.6,.1,.8]:
            box(f"DINORACE_SIDEPOD_{side}_{z}",(side*(cockpit_width/2+.18),.72,z),(.58,.62,.85),p["paint"],car,.15)
        box(f"DINORACE_INTAKE_{side}",(side*(cockpit_width/2+.18),.84,1.25),(.46,.3,.035),p["black"],car)
        for j in range(5):
            box(f"DINORACE_LOUVRE_{side}_{j}",(side*1.09,1.055,.4-j*.2),(.4,.02,.065),p["carbon"],car)
        rod(f"DINORACE_HALO_{side}",(side*cockpit_width/2,1.25,-.85),(side*cockpit_width/2,1.55,.95),.065,p["metal"],car)
        rod(f"DINORACE_HALO_PILLAR_{side}",(side*cockpit_width/2,1.5,.95),(side*.42,.85,1.6),.06,p["metal"],car)
        for z,label in [(wb/2,"F"),(-wb/2,"R")]:
            name = f"DINORACE_WHEEL_{label}{'L' if side<0 else 'R'}"
            wheel = group(name,car)
            # Child vertices are local so spinning the named group rotates around its axle.
            from geometry import xyz
            wheel.location = xyz((side*tw/2,.69,z))
            rod(name+"_TYRE",(-.39,0,0),(.39,0,0),.69,p["rubber"],wheel,segments=48)
            rod(name+"_RIM",(side*.395,0,0),(side*.41,0,0),.43,p["metal"],wheel,segments=40)
            rod(name+"_HUB",(side*.415,0,0),(side*.44,0,0),.22,p["carbon"],wheel,segments=24)
            for i in range(16):
                a = 2*math.pi*i/16
                rod(name+f"_SPOKE_{i}",(side*.425,math.sin(a)*.23,math.cos(a)*.23),(side*.425,math.sin(a)*.4,math.cos(a)*.4),.016,p["carbon"],wheel,segments=5)
            for anchor in [-.45,.45]:
                rod(f"DINORACE_SUSPENSION_{label}_{side}_{anchor}",(side*.6,.58,z+anchor),(side*tw/2,.69,z),.035,p["metal"],car)
    for j in range(3):
        box(f"DINORACE_FRONT_WING_{j}",(0,.32+j*.095,3.3-j*.23),(4.6,.075,.26),p["carbon"] if j==0 else p["paint"],car)
    for side in [-1,1]:
        box(f"DINORACE_ENDPLATE_{side}",(side*2.24,.48,3.1),(.07,.5,.94),p["paint"],car)
        rod(f"DINORACE_REAR_STAY_{side}",(side*.7,.45,-2.4),(side*.7,1.65,-2.9),.06,p["carbon"],car)
        box(f"DINORACE_REAR_ENDPLATE_{side}",(side*1.48,1.65,-2.95),(.075,.75,.85),p["paint"],car)
    for j in range(2):
        box(f"DINORACE_REAR_WING_{j}",(0,1.57+j*.25,-2.95),(3,.09,.65),p["carbon"],car)
    for i in range(7):
        box(f"DINORACE_DIFFUSER_{i}",(-1.2+i*.4,.39,-3.2),(.04,.33,.75),p["carbon"],car)
    box("DINORACE_RAIN_LIGHT",(0,.58,-3.61),(.22,.15,.05),p["red"],car)
    box("DINORACE_NOSE_STRIPE",(0,.89,1.75),(.16,.018,1.55),p["white"],car)
    # Mesh lettering, generated by Blender and embedded in the asset.
    import bpy
    from geometry import xyz
    curve = bpy.data.curves.new("DR_01_LETTERING","FONT")
    curve.body,curve.size,curve.extrude = "DR-01",.28,.001
    text = bpy.data.objects.new("DINORACE_LIVERY",curve)
    bpy.context.collection.objects.link(text)
    text.location = xyz((-.48,1.025,2.65))
    text.data.materials.append(p["white"])
    text.parent = car
    evaluated = text.evaluated_get(bpy.context.evaluated_depsgraph_get())
    text_mesh = bpy.data.meshes.new_from_object(evaluated)
    replacement = bpy.data.objects.new("DINORACE_LIVERY_MESH",text_mesh)
    bpy.context.collection.objects.link(replacement)
    replacement.matrix_world, replacement.parent = text.matrix_world, car
    bpy.data.objects.remove(text,do_unlink=True)
    return car
